sonar.projectKey=projet-10
sonar.organization=openclassrooms-java-angular
sonar.host.url=https://sonarcloud.io

# SOURCES
sonar.sources=back/src/main/java,front/src/app

# TESTS
sonar.tests=back/src/test/java

# TEST COVERAGE
sonar.test.inclusions=front/src/app/**/*.spec.ts,back/src/test/java/**/*Test.java,back/src/test/java/**/*Tests.java

# EXCLUSIONS
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.DS_Store,**/*.spec.ts

# coverage (Jacoco + Karma)
sonar.javascript.lcov.reportPaths=front/coverage/lcov.info
sonar.java.binaries=back/target/classes
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

# encodage
sonar.sourceEncoding=UTF-8