sonar.projectKey=ton_project_key
sonar.organization=openclassrooms-java-angular

sonar.host.url=https://sonarcloud.io

# sources
sonar.sources=back/src/main/java,front/src

# exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**

# coverage (Jacoco + Karma)
sonar.javascript.lcov.reportPaths=front/coverage/lcov.info
sonar.java.binaries=back/target/classes

# tests (optionnel mais recommandé)
sonar.tests=back/src/test,front/src

# encodage
sonar.sourceEncoding=UTF-8