sonar.projectKey=projet-10
sonar.organization=openclassrooms-java-angular
sonar.host.url=https://sonarcloud.io

# SOURCES
sonar.sources=back/src/main/java,front/src/app

# TESTS
sonar.tests=back/src/test/java

# FRONT TEST COVERAGE
sonar.test.inclusions=**/*.spec.ts,**/*Test.java

# EXCLUSIONS
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.DS_Store

# coverage (Jacoco + Karma)
sonar.javascript.lcov.reportPaths=front/coverage/lcov.info
sonar.java.binaries=back/target/classes

# encodage
sonar.sourceEncoding=UTF-8