sonar.projectKey=openclassrooms-java-angular_projet-10-back
sonar.organization=openclassrooms-java-angular
sonar.host.url=https://sonarcloud.io

# SOURCES
sonar.sources=src/main/java

# TESTS
sonar.tests=src/test/java

# coverage (Jacoco + Karma)
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# encodage
sonar.sourceEncoding=UTF-8