sonar.projectKey=projet-10-front
sonar.organization=openclassrooms-java-angular
sonar.host.url=https://sonarcloud.io

# SOURCES
sonar.sources=src/app

# TESTS
sonar.tests=src/app

sonar.test.inclusions=src/app/**/*.spec.ts
sonar.exclusions=src/app/**/*.spec.ts,**/node_modules/**,**/dist/**

# TEST COVERAGE
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# encodage
sonar.sourceEncoding=UTF-8s
