name: deploy-dockerhub

on:
  workflow_dispatch: # permet de déclencher manuellement le workflow
  workflow_run:
    workflows: ["sonar"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Active Docker Buildx pour permettre l'utilisation du cache GitHub Actions
      # et optimiser les performances des builds Docker (multi-stage + cache layers)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # =========================
      # BACKEND IMAGE
      # =========================
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # =========================
      # FRONTEND IMAGE
      # =========================
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max