name: sonar

on:
  workflow_dispatch: # permet de déclencher manuellement le workflow
  workflow_run:
    workflows: ["tests-backend", "tests-frontend"]
    types:
      - completed

jobs:
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # ---- FRONT ----
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Install front dependencies
        working-directory: front
        run: npm install

      - name: Install Chrome dependencies
        run: sudo apt-get update && sudo apt-get install -y libgbm-dev

      - name: Run front tests with coverage
        working-directory: front
        run: npm run test -- --watch=false --browsers=ChromeHeadlessCI --code-coverage

      - name: Verify coverage file exists
        run: |
          test -f ../front/coverage/lcov.info
          grep -q "SF:" front/coverage/lcov.info

      # ---- SONAR ----
      - name: Sonar analysis (Maven)
        working-directory: back
        run: mvn -B clean verify sonar:sonar \
          -Dsonar.projectKey=projet-10 \
          -Dsonar.organization=openclassrooms-java-angular \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}